Generate get secret, inform which secret failed to fetch

diff --git a/src/scripts/generate_get_secret b/src/scripts/generate_get_secret
--- a/src/scripts/generate_get_secret
+++ b/src/scripts/generate_get_secret
@@ -12,6 +12,7 @@ exit_code="$?"
 rm /tmp/TE_SAFE_TOKEN
 if [ $exit_code -gt 0 ]; then
     echo "$output" >&2
+    echo "Failed to fetch local secret $1" >&2
     exit $exit_code
 fi
 printf "%s" "$output"
@@ -32,6 +33,7 @@ exit_code="$?"
 rm /tmp/TE_SAFE_TOKEN
 if [ $exit_code -gt 0 ]; then
     echo "$output" >&2
+    echo "Failed to fetch local secret $1" >&2
     exit $exit_code
 fi
 printf "%s" "$output"
